import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Header";
import Footer from "@/components/Footer";
import {ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton} from "@clerk/nextjs"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

      <Nav/>
      <ClerkProvider>    
          {children}
    </ClerkProvider>
        <Footer/>
      </body>
    </html>
  );
}
